---
sidebar: sidebar 
permalink: about/whats-new.html 
keywords: whats new, enhancements, new features 
summary: NetApp aggiorna regolarmente le soluzioni di automazione, le API REST DEI prodotti e il software correlato per offrire nuove funzionalità, miglioramenti e correzioni dei bug. 
---
= Novità di automazione NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp aggiorna regolarmente le soluzioni di automazione, le API REST DEI prodotti e il software correlato per offrire nuove funzionalità, miglioramenti e correzioni dei bug.



== 27 luglio 2023

.Cloud Volumes ONTAP
Il supporto per Cloud Volumes ONTAP è organizzato dall'ambiente di cloud pubblico. È prevista una nuova soluzione per il seguente ambiente cloud:

* link:../solutions/cvo-gcp-burst-to-cloud.html["Cloud Volumes ONTAP per Google Cloud - burst nel cloud"]




== 04 giugno 2023

IL https://console.netapp.com/automationCatalog["Catalogo di automazione della console NetApp"^] è disponibile tramite l'interfaccia utente web della Console.  Il catalogo di automazione fornisce accesso a soluzioni che possono aiutarti con l'implementazione e l'integrazione automatizzate dei prodotti NetApp .  La documentazione per queste soluzioni è organizzata in diverse aree di prodotto o funzionali, come descritto di seguito.

.Gestione Amazon FSx for NetApp ONTAP
Di seguito vengono fornite due soluzioni di gestione Amazon FSx for NetApp ONTAP :

* link:../solutions/fsxn-burst-to-cloud.html["Gestione Amazon FSx for NetApp ONTAP - Burst to cloud"]
* link:../solutions/fsxn-disaster-recovery.html["Gestione di Amazon FSx for NetApp ONTAP - Ripristino di emergenza"]


.Azure NetApp Files
È inclusa una soluzione per facilitare la distribuzione di Oracle con Azure NetApp Files:

* link:../solutions/anf-oracle.html["Oracle con Azure NetApp Files"]


.Cloud Volumes ONTAP
Il supporto per Cloud Volumes ONTAP è organizzato dall'ambiente di cloud pubblico. Le soluzioni iniziali sono fornite per due ambienti cloud come segue:

* link:../solutions/cvo-aws-burst-to-cloud.html["Cloud Volumes ONTAP AWS - burst nel cloud"]
* link:../solutions/cvo-azure-burst-to-cloud.html["Cloud Volumes ONTAP, Azure - burst nel cloud"]

