---
sidebar: sidebar 
permalink: api/bluexp.html 
keywords: netapp products, product api, rest, rest api, bluexp, bluexp control plane 
summary: 'NetApp BlueXP  BlueXP  è un pannello di controllo unificato che offre una piattaforma multicloud ibrida per l"amministrazione dei servizi dati e dello storage in ambienti cloud pubblici e on-premise. È composto da diversi servizi o componenti distinti, ciascuno dei quali espone un"API REST associata. Consulta la documentazione e le risorse correlate fornite di seguito per iniziare con l"automazione del tuo ambiente BlueXP .' 
---
= Piano di controllo BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP  BlueXP  è un pannello di controllo unificato che offre una piattaforma multicloud ibrida per l'amministrazione dei servizi dati e dello storage in ambienti cloud pubblici e on-premise. È composto da diversi servizi o componenti distinti, ciascuno dei quali espone un'API REST associata. Consulta la documentazione e le risorse correlate fornite di seguito per iniziare con l'automazione del tuo ambiente BlueXP  utilizzando le API REST BlueXP .

.API REST BlueXP 
Puoi utilizzare le varie API REST per automatizzare l'amministrazione dello storage e dei servizi dati gestiti da BlueXP .

* https://docs.netapp.com/us-en/bluexp-automation/["Documentazione dell'API BlueXP"^]


.Famiglia BlueXP 
La documentazione della famiglia BlueXP  include tutto ciò che serve per iniziare a utilizzare il piano di controllo BlueXP .

* https://docs.netapp.com/us-en/bluexp-family/["Documentazione BlueXP"^]

