---
sidebar: sidebar 
permalink: api/bluexp.html 
keywords: netapp products, product api, rest, rest api, bluexp, bluexp control plane 
summary: 'NetApp BlueXP è un piano di controllo unificato che fornisce una piattaforma multi-cloud ibrida per la gestione di servizi di archiviazione e dati sia in ambienti on-premise che cloud pubblici.  È composto da diversi servizi o componenti distinti, ognuno dei quali espone un"API REST associata.  Per iniziare ad automatizzare il tuo ambiente BlueXP , consulta la documentazione e le risorse correlate fornite di seguito.' 
---
= Piano di controllo BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP è un piano di controllo unificato che fornisce una piattaforma multi-cloud ibrida per la gestione di servizi di archiviazione e dati sia in ambienti on-premise che cloud pubblici.  È composto da diversi servizi o componenti distinti, ognuno dei quali espone un'API REST associata.  Per iniziare ad automatizzare il tuo ambiente BlueXP utilizzando le API REST BlueXP , consulta la documentazione e le risorse correlate fornite di seguito.

.API REST BlueXP 
È possibile utilizzare le varie API REST per automatizzare l'amministrazione dei servizi di archiviazione e dati gestiti da BlueXP.

* https://docs.netapp.com/us-en/bluexp-automation/["Documentazione dell'API BlueXP"^]


.Famiglia BlueXP 
La documentazione della famiglia BlueXP  include tutto ciò che serve per iniziare a utilizzare il piano di controllo BlueXP .

* https://docs.netapp.com/us-en/bluexp-family/["Documentazione BlueXP"^]

